project:
  type: website
  output-dir: docs

website:
    navbar:
      left:
      - href: index1.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Posts.qmd
        text: Blog
      - text: Tutorial
        menu:
         - text: "{{< fa tree >}} Meta-analysis in R" 
           href: MetaR.qmd
         - text: "{{< fa chart-line >}} Data visualisation"  
           href: Datavis.qmd        
      right:
      - text: "{{< fa paper-plane >}} get in touch!"  
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/nipun_shrestha
          - icon: linkedin
            text: Linkedin
            href: https://www.linkedin.com/in/nipun-shrestha-a4903887/
          - icon: envelope
            text: Email
            href: mailto:drnipunsth@gmail.com
      tools: 
      - icon: github
        text: Github
        href: https://github.com/Nipun-Shrestha
    page-navigation: true
    back-to-top-navigation: true
    reader-mode: true
    page-footer:
      center: |
        <span class="container"><strong>[Contact Nipun Shrestha](mailto:drnipunsth@gmail.com){target="_blank"}</strong></span>
      left: |
        <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
      right: |
        <span class="container"><strong>[Github Repo](https://github.com/Nipun-Shrestha/Profile_page){target="_blank"}</strong></span>
      background: "#306A9E"
twitter-card: 
    creator: "@nipun_shrestha"
    image: "https://github.com/Nipun-Shrestha/Profile_page/blob/main/thumbnail.png"

open-graph:
    image: "https://github.com/Nipun-Shrestha/Profile_page/blob/main/thumbnail.png"
    locale: en_US
    
google-analytics: 
  tracking-id: "G-EY5KG3VY2K"
  cookie-consent: true
  anonymize-ip: true

execute:
  freeze: true

format:
  html:
    theme: 
      cosmo
      styles.css
      mainfont:Nunito Sans
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="2yr2KIypX7Kvr8Hn1g1YojGA6ZipA8o6h-3daP-uNGQ" />
    toc: true
editor: visual
